import pathlib

code = (
    "import os\n"
    "import uuid\n"
    "from datetime import datetime\n"
    "from telegram import Update, Bot\n"
    "from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes\n"
    "from core.database import SessionLocal, TelegramMessageModel, ReportModel, GoalModel, PriorityModel, ExecutivePriorityModel, DecisionMemoryModel, TimelineModel\n\n"
    "TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN', '8668242201:AAENQTquDPzLwGFvCsKGYhHbIucXWIv-CdU')\n"
    "TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '7859486600')\n\n"
    "def save_message(sender, message, direction):\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        record = TelegramMessageModel(\n"
    "            id=str(uuid.uuid4()),\n"
    "            sender=sender,\n"
    "            message=message,\n"
    "            direction=direction,\n"
    "            created_at=datetime.utcnow(),\n"
    "        )\n"
    "        db.add(record)\n"
    "        db.commit()\n"
    "    except Exception as e:\n"
    "        db.rollback()\n"
    "        print(f'Error saving message: {e}')\n"
    "    finally:\n"
    "        db.close()\n\n"
    "def is_authorized(chat_id):\n"
    "    return str(chat_id) == str(TELEGRAM_CHAT_ID)\n\n"
    "async def cmd_status(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/status', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        reports = db.query(ReportModel).count()\n"
    "        goals = db.query(GoalModel).filter(GoalModel.status == 'ACTIVE').count()\n"
    "        exec_priorities = db.query(ExecutivePriorityModel).filter(ExecutivePriorityModel.status == 'pending').count()\n"
    "        critical = db.query(ExecutivePriorityModel).filter(ExecutivePriorityModel.priority_level == 'CRITICAL', ExecutivePriorityModel.status == 'pending').count()\n"
    "        text = '\U0001f9e0 <b>CEREBRO STATUS</b>\n\n\U0001f4cb Reportes totales: ' + str(reports) + '\n\U0001f3af Metas activas: ' + str(goals) + '\n\u26a1 Prioridades ejecutivas pendientes: ' + str(exec_priorities) + '\n\U0001f6a8 Criticas sin resolver: ' + str(critical) + '\n\n\u2705 Sistema operacional'\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_reportes(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/reportes', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        records = db.query(ReportModel).order_by(ReportModel.created_at.desc()).limit(5).all()\n"
    "        if not records:\n"
    "            text = '\U0001f4cb No hay reportes aun.'\n"
    "        else:\n"
    "            lines = ['\U0001f4cb <b>ULTIMOS REPORTES</b>\n']\n"
    "            for r in records:\n"
    "                lines.append('- <b>' + r.agent + '</b> [' + r.priority + '] -- ' + r.message[:80])\n"
    "            text = '\n'.join(lines)\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_metas(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/metas', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        records = db.query(GoalModel).filter(GoalModel.status == 'ACTIVE').limit(5).all()\n"
    "        if not records:\n"
    "            text = '\U0001f3af No hay metas activas.'\n"
    "        else:\n"
    "            lines = ['\U0001f3af <b>METAS ACTIVAS</b>\n']\n"
    "            for r in records:\n"
    "                lines.append('- ' + r.title)\n"
    "            text = '\n'.join(lines)\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_prioridades(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/prioridades', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        records = db.query(ExecutivePriorityModel).filter(ExecutivePriorityModel.status == 'pending').order_by(ExecutivePriorityModel.created_at.desc()).limit(5).all()\n"
    "        if not records:\n"
    "            text = '\u26a1 No hay prioridades ejecutivas pendientes.'\n"
    "        else:\n"
    "            lines = ['\u26a1 <b>PRIORIDADES EJECUTIVAS PENDIENTES</b>\n']\n"
    "            for r in records:\n"
    "                emoji = '\U0001f6a8' if r.priority_level == 'CRITICAL' else '\U0001f534' if r.priority_level == 'HIGH' else '\U0001f7e1'\n"
    "                lines.append(emoji + ' <b>' + r.title + '</b> [' + r.priority_level + ']\n   ' + (r.description[:80] if r.description else ''))\n"
    "            text = '\n'.join(lines)\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_decisions(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/decisions', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        records = db.query(DecisionMemoryModel).order_by(DecisionMemoryModel.created_at.desc()).limit(5).all()\n"
    "        if not records:\n"
    "            text = '\U0001f9e0 No hay decisiones registradas.'\n"
    "        else:\n"
    "            lines = ['\U0001f9e0 <b>ULTIMAS DECISIONES</b>\n']\n"
    "            for r in records:\n"
    "                lines.append('- <b>' + r.topic + '</b>\n   ' + r.decision[:100])\n"
    "            text = '\n'.join(lines)\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_timeline(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/timeline', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        records = db.query(TimelineModel).order_by(TimelineModel.created_at.desc()).limit(7).all()\n"
    "        if not records:\n"
    "            text = '\U0001f4c5 No hay eventos en el timeline.'\n"
    "        else:\n"
    "            lines = ['\U0001f4c5 <b>TIMELINE RECIENTE</b>\n']\n"
    "            for r in records:\n"
    "                emoji = '\U0001f6a8' if r.importance == 'CRITICAL' else '\U0001f534' if r.importance == 'HIGH' else '\U0001f4cc'\n"
    "                fecha = r.created_at.strftime('%d/%m %H:%M')\n"
    "                lines.append(emoji + ' <b>' + r.title + '</b> [' + fecha + ']\n   ' + (r.description[:80] if r.description else ''))\n"
    "            text = '\n'.join(lines)\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def cmd_resumen(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    save_message(str(update.effective_chat.id), '/resumen', 'incoming')\n"
    "    db = SessionLocal()\n"
    "    try:\n"
    "        reports = db.query(ReportModel).count()\n"
    "        goals_active = db.query(GoalModel).filter(GoalModel.status == 'ACTIVE').count()\n"
    "        goals_done = db.query(GoalModel).filter(GoalModel.status == 'COMPLETED').count()\n"
    "        exec_pending = db.query(ExecutivePriorityModel).filter(ExecutivePriorityModel.status == 'pending').count()\n"
    "        critical = db.query(ExecutivePriorityModel).filter(ExecutivePriorityModel.priority_level == 'CRITICAL', ExecutivePriorityModel.status == 'pending').count()\n"
    "        decisions = db.query(DecisionMemoryModel).count()\n"
    "        last_report = db.query(ReportModel).order_by(ReportModel.created_at.desc()).first()\n"
    "        last_text = last_report.agent + ': ' + last_report.message[:60] if last_report else 'Sin reportes'\n"
    "        text = '\U0001f9e0 <b>RESUMEN EJECUTIVO CEREBRO</b>\n\n\U0001f4cb Reportes: ' + str(reports) + '\n\U0001f3af Metas activas: ' + str(goals_active) + ' | Completadas: ' + str(goals_done) + '\n\u26a1 Prioridades ejecutivas pendientes: ' + str(exec_pending) + '\n\U0001f6a8 Criticas: ' + str(critical) + '\n\U0001f9e0 Decisiones registradas: ' + str(decisions) + '\n\n\U0001f4cc Ultimo reporte:\n' + last_text\n"
    "    finally:\n"
    "        db.close()\n"
    "    await update.message.reply_text(text, parse_mode='HTML')\n"
    "    save_message('CEREBRO', text, 'outgoing')\n\n"
    "async def handle_message(update, context):\n"
    "    if not is_authorized(update.effective_chat.id):\n"
    "        return\n"
    "    text = update.message.text\n"
    "    save_message(str(update.effective_chat.id), text, 'incoming')\n"
    "    from core.response_engine import process_ceo_message\n"
    "    await update.message.chat.send_action('typing')\n"
    "    response = await process_ceo_message(text)\n"
    "    await update.message.reply_text(response, parse_mode='HTML')\n"
    "    save_message('CEREBRO', response, 'outgoing')\n\n"
    "def build_app():\n"
    "    application = Application.builder().token(TELEGRAM_TOKEN).build()\n"
    "    application.add_handler(CommandHandler('start', cmd_status))\n"
    "    application.add_handler(CommandHandler('status', cmd_status))\n"
    "    application.add_handler(CommandHandler('resumen', cmd_resumen))\n"
    "    application.add_handler(CommandHandler('reportes', cmd_reportes))\n"
    "    application.add_handler(CommandHandler('metas', cmd_metas))\n"
    "    application.add_handler(CommandHandler('prioridades', cmd_prioridades))\n"
    "    application.add_handler(CommandHandler('priorities', cmd_prioridades))\n"
    "    application.add_handler(CommandHandler('decisions', cmd_decisions))\n"
    "    application.add_handler(CommandHandler('timeline', cmd_timeline))\n"
    "    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))\n"
    "    return application\n"
)

import pathlib
pathlib.Path("core/telegram_handler.py").write_text(code, encoding="utf-8")
print("Escrito correctamente.")